
create or replace dynamic table DW_TEST.TEST.STATISTICS_GAME(
	AGGREGATED_AT,
	WEEKLY_AGGREGATED_AT,
	MONTHLY_AGGREGATED_AT,
	GP_ID,
	GGPASS_ID,
	BRAND_ID,
	SITE_ID,
	USER_ID WITH TAG (MGMT.GOV.TEST_GP_ID_TAG='TEST_GP_ID_MASK'),
	NICKNAME,
	COUNTRY_ID,
	GAME_TYPE,
	GAME_CLASS,
	IS_PLAY_MONEY,
	IS_PRIVATE,
	IS_FEATURED,
	IS_STAKING,
	TRUE_RAKE_OR_FEE,
	APPLIED_RAKE_OR_FEE,
	V_RAKE_OR_FEE,
	RAKE_OR_FEE,
	TICKET_REFUND_FEE,
	TICKET_REFUND,
	TAX_FEE,
	ADMIN_FEE,
	PROFIT_AND_LOSS,
	PROFIT_AND_LOSS_POKER,
	PROFIT_AND_LOSS_POKER_GAME,
	PROFIT_AND_LOSS_POKER_AOF_BINGO,
	PROFIT_AND_LOSS_POKER_AOF_FORTUNE_JACKPOT,
	PROFIT_AND_LOSS_POKER_AOF_HOLDEM_FORTUNE_JACKPOT,
	PROFIT_AND_LOSS_POKER_AOF_OMAHA_FORTUNE_JACKPOT,
	PROFIT_AND_LOSS_POKER_AOF_JACKPOT,
	PROFIT_AND_LOSS_POKER_BAD_BEAT_JACKPOT,
	PROFIT_AND_LOSS_POKER_BOUNTY_JACKPOT,
	PROFIT_AND_LOSS_POKER_CASHBACK,
	PROFIT_AND_LOSS_POKER_SNG_REWARD,
	PROFIT_AND_LOSS_POKER_STAKING,
	PROFIT_AND_LOSS_POKER_TICKET_REFUND,
	PROFIT_AND_LOSS_POKER_PROP_BET,
	PROFIT_AND_LOSS_POKER_TIME_BANK_CARD,
	PROFIT_AND_LOSS_SIDE_GAME,
	FISH_BUFFET_CONTRIBUTION,
	SPIN_AND_GOLD_POINT,
	NETWORK_GIVEAWAY,
	NETWORK_GIVEAWAY_CASH,
	NETWORK_GIVEAWAY_CASH_LEADERBOARD,
	NETWORK_GIVEAWAY_CASH_MONTHLY_RACE,
	NETWORK_GIVEAWAY_CASH_SEASON_PROMOTION,
	NETWORK_GIVEAWAY_CASH_DAILY_MISSION,
	NETWORK_GIVEAWAY_CASH_TOURNAMENT_BUBBLE,
	NETWORK_GIVEAWAY_CASH_TOURNAMENT_EARLY_BIRD,
	NETWORK_GIVEAWAY_CASH_RUSH_AND_CASH_EXTRA_DROP,
	NETWORK_GIVEAWAY_CASH_RED_ENVELOPE,
	NETWORK_GIVEAWAY_CASH_POKER_REWARD,
	NETWORK_GIVEAWAY_CASH_WINTER_PROMOTION,
	NETWORK_GIVEAWAY_CASH_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	NETWORK_GIVEAWAY_CASH_PROMOTION,
	NETWORK_GIVEAWAY_GCD,
	NETWORK_GIVEAWAY_GCD_MANUAL_REGISTRATION,
	NETWORK_GIVEAWAY_GCD_LEADERBOARD,
	NETWORK_GIVEAWAY_GCD_MONTHLY_RACE,
	NETWORK_GIVEAWAY_GCD_SEASON_PROMOTION,
	NETWORK_GIVEAWAY_GCD_DAILY_MISSION,
	NETWORK_GIVEAWAY_GCD_TOURNAMENT_BUBBLE,
	NETWORK_GIVEAWAY_GCD_TOURNAMENT_EARLY_BIRD,
	NETWORK_GIVEAWAY_GCD_RED_ENVELOPE,
	NETWORK_GIVEAWAY_GCD_POKER_REWARD,
	NETWORK_GIVEAWAY_GCD_WINTER_PROMOTION,
	NETWORK_GIVEAWAY_GCD_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	NETWORK_GIVEAWAY_GCD_PROMOTION,
	NETWORK_GIVEAWAY_GTD,
	NETWORK_GIVEAWAY_GTD_MANUAL_REGISTRATION,
	NETWORK_GIVEAWAY_GTD_LEADERBOARD,
	NETWORK_GIVEAWAY_GTD_MONTHLY_RACE,
	NETWORK_GIVEAWAY_GTD_SEASON_PROMOTION,
	NETWORK_GIVEAWAY_GTD_DAILY_MISSION,
	NETWORK_GIVEAWAY_GTD_TOURNAMENT_BUBBLE,
	NETWORK_GIVEAWAY_GTD_TOURNAMENT_EARLY_BIRD,
	NETWORK_GIVEAWAY_GTD_RED_ENVELOPE,
	NETWORK_GIVEAWAY_GTD_POKER_REWARD,
	NETWORK_GIVEAWAY_GTD_WINTER_PROMOTION,
	NETWORK_GIVEAWAY_GTD_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	NETWORK_GIVEAWAY_GTD_PROMOTION,
	NETWORK_GIVEAWAY_TICKET,
	NETWORK_GIVEAWAY_TICKET_TOURNAMENT_GIFT_BOX,
	NETWORK_GIVEAWAY_TICKET_MANUAL,
	NETWORK_GIVEAWAY_TICKET_LEADERBOARD,
	NETWORK_GIVEAWAY_TICKET_MONTHLY_RACE,
	NETWORK_GIVEAWAY_TICKET_SEASON_PROMOTION,
	NETWORK_GIVEAWAY_TICKET_POKER_BONUS,
	NETWORK_GIVEAWAY_TICKET_DAILY_MISSION,
	NETWORK_GIVEAWAY_TICKET_TOURNAMENT_BUBBLE,
	NETWORK_GIVEAWAY_TICKET_TOURNAMENT_EARLY_BIRD,
	NETWORK_GIVEAWAY_TICKET_RED_ENVELOPE,
	NETWORK_GIVEAWAY_TICKET_POKER_REWARD,
	NETWORK_GIVEAWAY_TICKET_WINTER_PROMOTION,
	NETWORK_GIVEAWAY_TICKET_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	NETWORK_GIVEAWAY_TICKET_CASH_GAME_REBUY_BONUS,
	NETWORK_GIVEAWAY_TICKET_REFUND,
	NETWORK_GIVEAWAY_TICKET_PROMOTION,
	BRAND_PROMOTION,
	BRAND_PROMOTION_CASH,
	BRAND_PROMOTION_CASH_WELCOME_BONUS,
	BRAND_PROMOTION_CASH_LEADERBOARD,
	BRAND_PROMOTION_CASH_MONTHLY_RACE,
	BRAND_PROMOTION_CASH_SEASON_PROMOTION,
	BRAND_PROMOTION_CASH_DAILY_MISSION,
	BRAND_PROMOTION_CASH_TOURNAMENT_BUBBLE,
	BRAND_PROMOTION_CASH_TOURNAMENT_EARLY_BIRD,
	BRAND_PROMOTION_CASH_RUSH_AND_CASH_EXTRA_DROP,
	BRAND_PROMOTION_CASH_RED_ENVELOPE,
	BRAND_PROMOTION_CASH_POKER_REWARD,
	BRAND_PROMOTION_CASH_WINTER_PROMOTION,
	BRAND_PROMOTION_CASH_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	BRAND_PROMOTION_CASH_POKER_BONUS,
	BRAND_PROMOTION_CASH_PROMOTION,
	BRAND_PROMOTION_GCD,
	BRAND_PROMOTION_GCD_MANUAL_REGISTRATION,
	BRAND_PROMOTION_GCD_LEADERBOARD,
	BRAND_PROMOTION_GCD_MONTHLY_RACE,
	BRAND_PROMOTION_GCD_SEASON_PROMOTION,
	BRAND_PROMOTION_GCD_DAILY_MISSION,
	BRAND_PROMOTION_GCD_TOURNAMENT_BUBBLE,
	BRAND_PROMOTION_GCD_TOURNAMENT_EARLY_BIRD,
	BRAND_PROMOTION_GCD_RED_ENVELOPE,
	BRAND_PROMOTION_GCD_POKER_REWARD,
	BRAND_PROMOTION_GCD_WINTER_PROMOTION,
	BRAND_PROMOTION_GCD_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	BRAND_PROMOTION_GCD_POKER_BONUS,
	BRAND_PROMOTION_GCD_PROMOTION,
	BRAND_PROMOTION_GTD,
	BRAND_PROMOTION_GTD_MANUAL_REGISTRATION,
	BRAND_PROMOTION_GTD_LEADERBOARD,
	BRAND_PROMOTION_GTD_MONTHLY_RACE,
	BRAND_PROMOTION_GTD_SEASON_PROMOTION,
	BRAND_PROMOTION_GTD_DAILY_MISSION,
	BRAND_PROMOTION_GTD_TOURNAMENT_BUBBLE,
	BRAND_PROMOTION_GTD_TOURNAMENT_EARLY_BIRD,
	BRAND_PROMOTION_GTD_RED_ENVELOPE,
	BRAND_PROMOTION_GTD_POKER_REWARD,
	BRAND_PROMOTION_GTD_WINTER_PROMOTION,
	BRAND_PROMOTION_GTD_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	BRAND_PROMOTION_GTD_POKER_BONUS,
	BRAND_PROMOTION_GTD_PROMOTION,
	BRAND_PROMOTION_TICKET,
	BRAND_PROMOTION_TICKET_TOURNAMENT_GIFT_BOX,
	BRAND_PROMOTION_TICKET_MANUAL,
	BRAND_PROMOTION_TICKET_LEADERBOARD,
	BRAND_PROMOTION_TICKET_MONTHLY_RACE,
	BRAND_PROMOTION_TICKET_SEASON_PROMOTION,
	BRAND_PROMOTION_TICKET_DAILY_MISSION,
	BRAND_PROMOTION_TICKET_TOURNAMENT_BUBBLE,
	BRAND_PROMOTION_TICKET_TOURNAMENT_EARLY_BIRD,
	BRAND_PROMOTION_TICKET_RED_ENVELOPE,
	BRAND_PROMOTION_TICKET_POKER_REWARD,
	BRAND_PROMOTION_TICKET_WINTER_PROMOTION,
	BRAND_PROMOTION_TICKET_SPIN_AND_GOLD_GO_FOR_GOLD_PROMOTION,
	BRAND_PROMOTION_TICKET_CASH_GAME_REBUY_BONUS,
	BRAND_PROMOTION_TICKET_POKER_BONUS,
	BRAND_PROMOTION_TICKET_REFUND,
	BRAND_PROMOTION_TICKET_PROMOTION,
	TOURNAMENT_OVERLAY,
	TOURNAMENT_OVERLAY_PLAYER_DEDUCTED,
	TOURNAMENT_OVERLAY_PLAYER_NON_DEDUCTED,
	TOURNAMENT_OVERLAY_PLAYER,
	TOURNAMENT_OVERLAY_BRAND,
	TOURNAMENT_OVERLAY_NEIF,
	TOURNAMENT_OVERLAY_ADJUSTMENT,
	CASINO_PROMOTION_NETWORK,
	CASINO_PROMOTION_BRAND_AGENT,
	CASINO_PROMOTION_BRAND,
	CASINO_PROMOTION_AGENT,
	RAKE_DIFFERENCE,
	SIDE_GAME_NETLOSS,
	JACKPOT_WIN,
	JACKPOT_CONTRIBUTION,
	JACKPOT_RECONCILIATION,
	PROMOTION_WIN,
	PROMOTION_CONTRIBUTION,
	PROMOTION_RECONCILIATION,
	CASINO_RECONCILIATION,
	TURNOVER,
	LICENSE_FEE,
	GGR,
	CROSS_CAGE,
	POKER_WINLOSS,
	NET_STATS,
	SESSION_COUNT,
	GAME_COUNT,
	RAKED_GAME_COUNT,
	NON_RAKED_GAME_COUNT,
	ALL_IN_COUNT,
	JACKPOT_COUNT,
	MAIN_EVENT_COUNT,
	OVERLAYED_COUNT,
	BUY_IN,
	BUY_IN_CASH,
	BUY_IN_GCD,
	BUY_IN_GTD,
	BUY_IN_TICKET,
	BUY_IN_EFFECTIVE,
	BUY_IN_CASH_COUNT,
	PAYOUT,
	PAYOUT_CASH,
	PAYOUT_GCD,
	PAYOUT_GTD,
	PAYOUT_TICKET,
	BET,
	BET_COUNT,
	ORIGINAL_V_RAKE_OR_FEE,
	ORIGINAL_RAKE_OR_FEE,
	ORIGINAL_RAKE_DIFFERENCE,
	ORIGINAL_GGR,
	ORIGINAL_ESTIMATED_GGR
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_CREATE warehouse = DT_GP1_WH
 as
SELECT   aggregated_at AS aggregated_at,
         -- week.
         date_trunc('WEEK', AGGREGATED_AT::DATE) AS weekly_aggregated_at,
         -- month.
         date_trunc('MONTH', AGGREGATED_AT::DATE) AS monthly_aggregated_at,
         -- account.
         gp_id,
         max(ggpass_id) as ggpass_id,
         brand_id,
         max(site_id) as site_id,
         max(user_id) as user_id,
         max(nickname) as nickname,
         max(country_id) as country_id,
         -- game.
         general_game_type AS game_type,
         game_class,
         is_play_money,
         is_private,
         is_featured,
         is_staking,
         -- stats.
         -- rakeOrFee.
         sum(round(true_rake_or_fee   / requested_exchange_rate * 1 , 8)) AS true_rake_or_fee,
         sum(round(applied_rake_or_fee/ requested_exchange_rate * 1 , 8)) AS applied_rake_or_fee,
         sum(round(v_rake_or_fee / requested_exchange_rate * 1 , 8)) AS v_rake_or_fee,
         sum(round(rake_or_fee        / requested_exchange_rate * 1 , 8)) AS rake_or_fee,
         sum(round(ticket_refund_fee  / requested_exchange_rate * 1 , 8)) AS ticket_refund_fee,
         sum(round(ticket_refund      / requested_exchange_rate * 1 , 8)) AS ticket_refund,
         -- taxFee.
         sum(round(tax_fee / requested_exchange_rate * 1 , 8)) AS tax_fee,
         -- adminFee.
         sum(round(admin_fee / requested_exchange_rate * 1 , 8)) AS admin_fee,
         -- profitAndLoss.
         sum(round(profit_and_loss / requested_exchange_rate * 1 , 8)) AS profit_and_loss,
         -- profitAndLossPoker.
         sum(round(profit_and_loss_poker                            / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker,
         sum(round(profit_and_loss_poker_game                       / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_game,
         sum(round(profit_and_loss_poker_aof_bingo                  / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_aof_bingo,
         sum(round(profit_and_loss_poker_aof_fortune_jackpot        / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_aof_fortune_jackpot,
         sum(round(profit_and_loss_poker_aof_holdem_fortune_jackpot / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_aof_holdem_fortune_jackpot,
         sum(round(profit_and_loss_poker_aof_omaha_fortune_jackpot  / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_aof_omaha_fortune_jackpot,
         sum(round(profit_and_loss_poker_aof_jackpot                / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_aof_jackpot,
         sum(round(profit_and_loss_poker_bad_beat_jackpot           / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_bad_beat_jackpot,
         sum(round(profit_and_loss_poker_bounty_jackpot             / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_bounty_jackpot,
         sum(round(profit_and_loss_poker_cashback                   / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_cashback,
         sum(round(profit_and_loss_poker_sng_reward                 / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_sng_reward,
         sum(round(profit_and_loss_poker_staking                    / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_staking,
         sum(round(profit_and_loss_poker_ticket_refund              / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_ticket_refund,
         sum(round(profit_and_loss_poker_prop_bet                   / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_prop_bet,
         sum(round(profit_and_loss_poker_time_bank_card                  / requested_exchange_rate * 1 , 8)) AS profit_and_loss_poker_time_bank_card,
         -- profitAndLossSideGame.
         sum(round(profit_and_loss_side_game / requested_exchange_rate * 1 , 8)) AS profit_and_loss_side_game,
         -- fishBuffet.
         sum(round(fish_buffet_contribution  / requested_exchange_rate * 1 , 8)) AS fish_buffet_contribution,
         -- spinAndGold.
         sum(spin_and_gold_point) AS spin_and_gold_point,
         -- networkGiveaway.
         sum(round(network_giveaway / requested_exchange_rate * 1 , 8)) AS network_giveaway,
         -- networkGiveawayCash.
         sum(round(network_giveaway_cash                                        / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash,
         sum(round(network_giveaway_cash_leaderboard                            / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_leaderboard,
         sum(round(network_giveaway_cash_monthly_race                           / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_monthly_race,
         sum(round(network_giveaway_cash_season_promotion                       / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_season_promotion,
         sum(round(network_giveaway_cash_daily_mission                          / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_daily_mission,
         sum(round(network_giveaway_cash_tournament_bubble                      / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_tournament_bubble,
         sum(round(network_giveaway_cash_tournament_early_bird                  / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_tournament_early_bird,
         sum(round(network_giveaway_cash_rush_and_cash_extra_drop               / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_rush_and_cash_extra_drop,
         sum(round(network_giveaway_cash_red_envelope                           / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_red_envelope,
         sum(round(network_giveaway_cash_poker_reward                           / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_poker_reward,
         sum(round(network_giveaway_cash_winter_promotion                       / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_winter_promotion,
         sum(round(network_giveaway_cash_spin_and_gold_go_for_gold_promotion    / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_spin_and_gold_go_for_gold_promotion,
         sum(round(network_giveaway_cash_promotion                              / requested_exchange_rate * 1 , 8)) AS network_giveaway_cash_promotion,
         -- networkGiveawayGcd.
         sum(round(network_giveaway_gcd                                         / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd,
         sum(round(network_giveaway_gcd_manual_registration                     / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_manual_registration,
         sum(round(network_giveaway_gcd_leaderboard                             / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_leaderboard,
         sum(round(network_giveaway_gcd_monthly_race                            / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_monthly_race,
         sum(round(network_giveaway_gcd_season_promotion                        / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_season_promotion,
         sum(round(network_giveaway_gcd_daily_mission                           / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_daily_mission,
         sum(round(network_giveaway_gcd_tournament_bubble                       / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_tournament_bubble,
         sum(round(network_giveaway_gcd_tournament_early_bird                   / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_tournament_early_bird,
         sum(round(network_giveaway_gcd_red_envelope                            / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_red_envelope,
         sum(round(network_giveaway_gcd_poker_reward                            / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_poker_reward,
         sum(round(network_giveaway_gcd_winter_promotion                        / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_winter_promotion,
         sum(round(network_giveaway_gcd_spin_and_gold_go_for_gold_promotion     / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_spin_and_gold_go_for_gold_promotion,
         sum(round(network_giveaway_gcd_promotion                               / requested_exchange_rate * 1 , 8)) AS network_giveaway_gcd_promotion,
         -- networkGiveawayGtd.
         sum(round(network_giveaway_gtd                                         / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd,
         sum(round(network_giveaway_gtd_manual_registration                     / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_manual_registration,
         sum(round(network_giveaway_gtd_leaderboard                             / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_leaderboard,
         sum(round(network_giveaway_gtd_monthly_race                            / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_monthly_race,
         sum(round(network_giveaway_gtd_season_promotion                        / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_season_promotion,
         sum(round(network_giveaway_gtd_daily_mission                           / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_daily_mission,
         sum(round(network_giveaway_gtd_tournament_bubble                       / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_tournament_bubble,
         sum(round(network_giveaway_gtd_tournament_early_bird                   / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_tournament_early_bird,
         sum(round(network_giveaway_gtd_red_envelope                            / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_red_envelope,
         sum(round(network_giveaway_gtd_poker_reward                            / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_poker_reward,
         sum(round(network_giveaway_gtd_winter_promotion                        / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_winter_promotion,
         sum(round(network_giveaway_gtd_spin_and_gold_go_for_gold_promotion     / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_spin_and_gold_go_for_gold_promotion,
         sum(round(network_giveaway_gtd_promotion                               / requested_exchange_rate * 1 , 8)) AS network_giveaway_gtd_promotion,
         -- networkGiveawayTicket.
         sum(round(network_giveaway_ticket                                      / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket,
         sum(round(network_giveaway_ticket_tournament_gift_box                       / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_tournament_gift_box,
         sum(round(network_giveaway_ticket_manual                                    / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_manual,
         sum(round(network_giveaway_ticket_leaderboard                               / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_leaderboard,
         sum(round(network_giveaway_ticket_monthly_race                              / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_monthly_race,
         sum(round(network_giveaway_ticket_season_promotion                          / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_season_promotion,
         sum(round(network_giveaway_ticket_poker_bonus                               / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_poker_bonus,
         sum(round(network_giveaway_ticket_daily_mission                             / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_daily_mission,
         sum(round(network_giveaway_ticket_tournament_bubble                         / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_tournament_bubble,
         sum(round(network_giveaway_ticket_tournament_early_bird                     / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_tournament_early_bird,
         sum(round(network_giveaway_ticket_red_envelope                              / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_red_envelope,
         sum(round(network_giveaway_ticket_poker_reward                              / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_poker_reward,
         sum(round(network_giveaway_ticket_winter_promotion                          / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_winter_promotion,
         sum(round(network_giveaway_ticket_spin_and_gold_go_for_gold_promotion       / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_spin_and_gold_go_for_gold_promotion,
         sum(round(network_giveaway_ticket_cash_game_rebuy_bonus                     / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_cash_game_rebuy_bonus,
         sum(round(network_giveaway_ticket_refund                                    / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_refund,
         sum(round(network_giveaway_ticket_promotion                                 / requested_exchange_rate * 1 , 8)) AS network_giveaway_ticket_promotion,
         -- brandPromotion.
         sum(round(brand_promotion / requested_exchange_rate * 1 , 8)) AS brand_promotion,
         -- brandPromotionCash.
         sum(round(brand_promotion_cash               / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash,
         sum(round(brand_promotion_cash_welcome_bonus / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_welcome_bonus,
         sum(round(brand_promotion_cash_leaderboard   / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_leaderboard,
         sum(round(brand_promotion_cash_monthly_race  / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_monthly_race,
         sum(round(brand_promotion_cash_season_promotion  / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_season_promotion,
         sum(round(brand_promotion_cash_daily_mission     / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_daily_mission,
         sum(round(brand_promotion_cash_tournament_bubble / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_tournament_bubble,
         sum(round(brand_promotion_cash_tournament_early_bird / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_tournament_early_bird,
         sum(round(brand_promotion_cash_rush_and_cash_extra_drop / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_rush_and_cash_extra_drop,
         sum(round(brand_promotion_cash_red_envelope      / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_red_envelope,
         sum(round(brand_promotion_cash_poker_reward      / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_poker_reward,
         sum(round(brand_promotion_cash_winter_promotion  / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_winter_promotion,
         sum(round(brand_promotion_cash_spin_and_gold_go_for_gold_promotion / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_spin_and_gold_go_for_gold_promotion,
         sum(round(brand_promotion_cash_poker_bonus   / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_poker_bonus,
         sum(round(brand_promotion_cash_promotion     / requested_exchange_rate * 1 , 8)) AS brand_promotion_cash_promotion,
         -- brandPromotionGcd.
         sum(round(brand_promotion_gcd                     / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd,
         sum(round(brand_promotion_gcd_manual_registration / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_manual_registration,
         sum(round(brand_promotion_gcd_leaderboard         / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_leaderboard,
         sum(round(brand_promotion_gcd_monthly_race        / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_monthly_race,
         sum(round(brand_promotion_gcd_season_promotion    / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_season_promotion,
         sum(round(brand_promotion_gcd_daily_mission       / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_daily_mission,
         sum(round(brand_promotion_gcd_tournament_bubble   / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_tournament_bubble,
         sum(round(brand_promotion_gcd_tournament_early_bird / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_tournament_early_bird,
         sum(round(brand_promotion_gcd_red_envelope        / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_red_envelope,
         sum(round(brand_promotion_gcd_poker_reward        / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_poker_reward,
         sum(round(brand_promotion_gcd_winter_promotion      / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_winter_promotion,
         sum(round(brand_promotion_gcd_spin_and_gold_go_for_gold_promotion / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_spin_and_gold_go_for_gold_promotion,
         sum(round(brand_promotion_gcd_poker_bonus         / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_poker_bonus,
         sum(round(brand_promotion_gcd_promotion           / requested_exchange_rate * 1 , 8)) AS brand_promotion_gcd_promotion,
         -- brandPromotionGtd.
         sum(round(brand_promotion_gtd                     / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd,
         sum(round(brand_promotion_gtd_manual_registration / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_manual_registration,
         sum(round(brand_promotion_gtd_leaderboard         / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_leaderboard,
         sum(round(brand_promotion_gtd_monthly_race        / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_monthly_race,
         sum(round(brand_promotion_gtd_season_promotion    / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_season_promotion,
         sum(round(brand_promotion_gtd_daily_mission       / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_daily_mission,
         sum(round(brand_promotion_gtd_tournament_bubble   / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_tournament_bubble,
         sum(round(brand_promotion_gtd_tournament_early_bird / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_tournament_early_bird,
         sum(round(brand_promotion_gtd_red_envelope        / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_red_envelope,
         sum(round(brand_promotion_gtd_poker_reward        / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_poker_reward,
         sum(round(brand_promotion_gtd_winter_promotion      / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_winter_promotion,
         sum(round(brand_promotion_gtd_spin_and_gold_go_for_gold_promotion / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_spin_and_gold_go_for_gold_promotion,
         sum(round(brand_promotion_gtd_poker_bonus         / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_poker_bonus,
         sum(round(brand_promotion_gtd_promotion           / requested_exchange_rate * 1 , 8)) AS brand_promotion_gtd_promotion,
         -- brandPromotionTicket.
         sum(round(brand_promotion_ticket                                       / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket,
         sum(round(brand_promotion_ticket_tournament_gift_box                   / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_tournament_gift_box,
         sum(round(brand_promotion_ticket_manual                                / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_manual,
         sum(round(brand_promotion_ticket_leaderboard                           / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_leaderboard,
         sum(round(brand_promotion_ticket_monthly_race                          / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_monthly_race,
         sum(round(brand_promotion_ticket_season_promotion                      / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_season_promotion,
         sum(round(brand_promotion_ticket_daily_mission                         / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_daily_mission,
         sum(round(brand_promotion_ticket_tournament_bubble                     / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_tournament_bubble,
         sum(round(brand_promotion_ticket_tournament_early_bird                 / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_tournament_early_bird,
         sum(round(brand_promotion_ticket_red_envelope                          / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_red_envelope,
         sum(round(brand_promotion_ticket_poker_reward                          / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_poker_reward,
         sum(round(brand_promotion_ticket_winter_promotion                      / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_winter_promotion,
         sum(round(brand_promotion_ticket_spin_and_gold_go_for_gold_promotion   / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_spin_and_gold_go_for_gold_promotion,
         sum(round(brand_promotion_ticket_cash_game_rebuy_bonus                 / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_cash_game_rebuy_bonus,
         sum(round(brand_promotion_ticket_poker_bonus                           / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_poker_bonus,
         sum(round(brand_promotion_ticket_refund                                / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_refund,
         sum(round(brand_promotion_ticket_promotion                             / requested_exchange_rate * 1 , 8)) AS brand_promotion_ticket_promotion,
         -- tournamentOverlay.
         sum(round(tournament_overlay                     / requested_exchange_rate * 1 , 8)) AS tournament_overlay,
         sum(round(tournament_overlay_player_deducted     / requested_exchange_rate * 1 , 8)) AS tournament_overlay_player_deducted,
         sum(round(tournament_overlay_player_non_deducted / requested_exchange_rate * 1 , 8)) AS tournament_overlay_player_non_deducted,
         sum(round(tournament_overlay_player              / requested_exchange_rate * 1 , 8)) AS tournament_overlay_player,
         sum(round(tournament_overlay_brand               / requested_exchange_rate * 1 , 8)) AS tournament_overlay_brand,
         sum(round(tournament_overlay_neif                / requested_exchange_rate * 1 , 8)) AS tournament_overlay_neif,
         sum(round(tournament_overlay_adjustment          / requested_exchange_rate * 1 , 8)) AS tournament_overlay_adjustment,
         -- casinoPromotion.
         0 AS casino_promotion_network,
         0 AS casino_promotion_brand_agent,
         0 AS casino_promotion_brand,
         0 AS casino_promotion_agent,
         -- rakeDifference.
         sum(round(rake_difference / requested_exchange_rate * 1 , 8)) AS rake_difference,
         -- sideGameNetloss.
         sum(round(side_game_netloss / requested_exchange_rate * 1 , 8)) AS side_game_netloss,
         -- jackpot.
         sum(round(jackpot_win            / requested_exchange_rate * 1 , 8)) AS jackpot_win,
         sum(round(jackpot_contribution   / requested_exchange_rate * 1 , 8)) AS jackpot_contribution,
         sum(round(jackpot_reconciliation / requested_exchange_rate * 1 , 8)) AS jackpot_reconciliation,
         -- promotion.
         sum(round(promotion_win            / requested_exchange_rate * 1 , 8)) AS promotion_win,
         sum(round(promotion_contribution   / requested_exchange_rate * 1 , 8)) AS promotion_contribution,
         sum(round(promotion_reconciliation / requested_exchange_rate * 1 , 8)) AS promotion_reconciliation,
         -- casinoReconciliation.
         0 AS casino_reconciliation,
         -- turnover.
         sum(round(turnover / requested_exchange_rate * 1 , 8)) AS turnover,
         -- licenseFee.
         sum(round(license_fee / requested_exchange_rate * 1 , 8)) AS license_fee,
         -- ggr.
         sum(round(ggr / requested_exchange_rate * 1 , 8)) AS ggr,
         -- crossCage.
         sum(round(cross_cage / requested_exchange_rate * 1 , 8)) AS cross_cage,
         -- pokerWinloss.
         sum(round(poker_winloss / requested_exchange_rate * 1 , 8)) AS poker_winloss,
         -- netStats.
         sum(round(net_stats / requested_exchange_rate * 1 , 8)) AS net_stats,
         -- count.
         sum(
                 CASE
                     WHEN user_session_id != '0'
                         AND      game_type IN ( 'HOLDEM' ,
                                                 'OMAHA' ,
                                                 'OMAHA_FIVE' ,
                                                 'OMAHA_SIX' ,
                                                 'LIMIT_OMAHA' ,
                                                 'AOF' ,
                                                 'AOF_OMAHA' ,
                                                 'RUSH_AND_CASH' ,
                                                 'RUSH_AND_CASH_OMAHA' ,
                                                 'SHORT_DECK' ,
                                                 'PROP_BET' ,
                                                 'SPIN_AND_GOLD' ,
                                                 'SPIN_AND_GOLD_6MAX' ,
                                                 'BATTLE_ROYALE' ,
                                                 'TOURNAMENT' ,
                                                 'WSOPPLUS_TOURNAMENT' ,
                                                 'BET_AND_GO' ,
                                                 'FLIP_AND_GO' ,
                                                 'AOF_HOLDEM_SIT_AND_GO' ,
                                                 'AOF_OMAHA_SIT_AND_GO' ,
                                                 'ROSHAMBO_HOLDEM' ,
                                                 'AVATAR_OMAHA' ) THEN 1
                     ELSE 0
                     end)                      AS session_count,
         sum(game_count)           AS game_count,
         sum(raked_game_count)     AS raked_game_count,
         sum(non_raked_game_count) AS non_raked_game_count ,
         sum(all_in_count)         AS all_in_count,
         sum(jackpot_count)        AS jackpot_count,
         sum(
                 CASE
                     WHEN is_main_event = TRUE THEN 1
                     ELSE 0
                     end) AS main_event_count,
         sum(
                 CASE
                     WHEN is_overlayed = TRUE THEN 1
                     ELSE 0
                     end)                                                                                                       AS overlayed_count,
         sum(round(buy_in        / requested_exchange_rate * 1 , 8))                                                AS buy_in,
         sum(round(buy_in_cash   / requested_exchange_rate * 1 , 8))                                                AS buy_in_cash,
         sum(round(buy_in_gcd    / requested_exchange_rate * 1 , 8))                                                AS buy_in_gcd,
         sum(round(buy_in_gtd    / requested_exchange_rate * 1 , 8))                                                AS buy_in_gtd,
         sum(round(buy_in_ticket / requested_exchange_rate * 1 , 8))                                                AS buy_in_ticket,
         sum( case when participant_count = 0 then 0 else truncate(ifnull(ranking / participant_count, 0), 8) * round(buy_in / requested_exchange_rate * 1 , 8) end) AS buy_in_effective,
         sum(
                 CASE
                     WHEN (
                              buy_in_cash + buy_in_gcd + buy_in_gtd) > 0 THEN 1
                     ELSE 0
                     end)                                                 AS buy_in_cash_count,
         sum(round(payout        / requested_exchange_rate * 1 , 8)) AS payout,
         sum(round(payout_cash   / requested_exchange_rate * 1 , 8)) AS payout_cash,
         sum(round(payout_gcd    / requested_exchange_rate * 1 , 8)) AS payout_gcd,
         sum(round(payout_gtd    / requested_exchange_rate * 1 , 8)) AS payout_gtd,
         sum(round(payout_ticket / requested_exchange_rate * 1 , 8)) AS payout_ticket,
         sum(round(bet           / requested_exchange_rate * 1 , 8)) AS bet,
         sum(bet_count)                                              AS bet_count

        , -- original rake related.
        SUM(ROUND(CASE WHEN site_id NOT IN ('GGPCZ', 'GGPBE', 'WSOPON')	AND requested_at >= '2024-12-15 08:00' AND requested_at < '2024-12-27 08:00' AND (brand_id != 'POKERARABIA' OR is_exclusive = 0) THEN 2 ELSE 1 END * v_rake_or_fee / requested_exchange_rate * 1 , 8)) AS original_v_rake_or_fee,
        SUM(ROUND(CASE WHEN site_id NOT IN ('GGPCZ', 'GGPBE', 'WSOPON')	AND requested_at >= '2024-12-15 08:00' AND requested_at < '2024-12-27 08:00' AND (brand_id != 'POKERARABIA' OR is_exclusive = 0) THEN 2 ELSE 1 END * rake_or_fee / requested_exchange_rate * 1 , 8)) AS original_rake_or_fee,
        SUM(ROUND(CASE WHEN site_id NOT IN ('GGPCZ', 'GGPBE', 'WSOPON') AND requested_at >= '2024-12-15 08:00' AND requested_at < '2024-12-27 08:00' AND (brand_id != 'POKERARABIA' OR is_exclusive = 0) THEN rake_difference -v_rake_or_fee ELSE rake_difference END / requested_exchange_rate * 1 , 8))  AS original_rake_difference,
        SUM(ROUND(CASE WHEN site_id NOT IN ('GGPCZ', 'GGPBE', 'WSOPON') AND requested_at >= '2024-12-15 08:00' AND requested_at < '2024-12-27 08:00' AND (brand_id != 'POKERARABIA' OR is_exclusive = 0) THEN rake_or_fee + ggr ELSE ggr END / requested_exchange_rate * 1 , 8)) AS original_ggr,
        SUM(ROUND(CASE WHEN site_id NOT IN ('GGPCZ', 'GGPBE', 'WSOPON') AND requested_at >= '2024-12-15 08:00' AND requested_at < '2024-12-27 08:00' AND (brand_id != 'POKERARABIA' OR is_exclusive = 0) THEN rake_or_fee + estimated_ggr ELSE estimated_ggr END / requested_exchange_rate * 1 , 8)) AS original_estimated_ggr

FROM     DW_ORIGIN_GLOBAL_TEST.GLOBAL_TEST_GP_STATS5_DB_STATS.STATISTICS_GAME_POKER_PER_SESSION
WHERE    requester_id NOT IN ('_TG', '_FS') -- AND game_id NOT IN ('0', '00000000000000000000000000000000')
GROUP BY
    -- day.
    aggregated_at ,
    -- account.
    gp_id,
    brand_id,
    general_game_type ,
    game_class,
    is_play_money,
    is_private,
    is_featured,
    is_staking
;
