version: 0.2

env:
  exported-variables:
    - GLUE_JOB_SCRIPT_URL

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - export GLUE_JOB_SCRIPT_URL="${SOURCE_SCRIPT_REPOSITORY_PREFIX}/${GLUE_JOB_NAME}_$(date '+%Y%m%d_%H%M%S').py"
      - export GLUE_JOB_SCRIPT_LOCAL_FILE=built-glue-job-script.py
      - export GLUE_JOB_CLOUDFORMATION_TEMPLATE_FILE=cloudformation-templates/glue-scheduled-job-stack-template.yaml
  build:
    commands:
      - cp $SOURCE_SCRIPT_FILE $GLUE_JOB_SCRIPT_LOCAL_FILE
      - aws s3 cp "${GLUE_JOB_SCRIPT_LOCAL_FILE}" "${GLUE_JOB_SCRIPT_URL}" --region ${DEPLOY_REGION}
      - 'sed "s%DefaultArguments: {}%DefaultArguments: $(echo $GLUE_JOB_PARAMETERS | jq -r tostring)%" "$GLUE_JOB_CLOUDFORMATION_TEMPLATE_FILE" > ./stack-template.yaml'
artifacts:
  type: zip
  files:
    - built-glue-job-script.py
    - stack-template.yaml
