-- 1. Create Tag
CREATE OR REPLACE TAG DW.GOV.DIVISION_EMAIL_TAG
         PROPAGATE = ON_DEPENDENCY_AND_DATA_MOVEMENT;

-- 2. Create Masking Policy
CREATE OR REPLACE MASKING POLICY DW.GOV.DIVISION_EMAIL_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('TEAM_ROLE') THEN val
        ...
        ELSE '***MASKED***'
    END;

-- 3. Alter Tag Set Masking Policy
ALTER TAG DW.GOV.DIVISION_EMAIL_TAG
    SET MASKING POLICY DW.GOV.DIVISION_EMAIL_MASK ;

-- 4. Alter Table Set TAG Propagation
ALTER TABLE DW_TEST.DIVISION_DBO.TABLENAME
	ALTER COLUMN EMAIL SET TAG DW.GOV.DIVISION_EMAIL_TAG = 'DIVISION_EMAIL_MASK';

